---
title: "Red and Black : Search for the Best"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data, echo = TRUE, results = 'hide'}
class_roll <- readRDS("./class_roll_masked_2402.RDS")
str(class_roll)
names(class_roll) <- c("college", "dept", "id", "name", "status", "email", "cell_no")
class_roll$status <- ifelse(is.na(class_roll$status), "휴학", class_roll$status)
str(class_roll)
source("./RnB_2024_v5.R")
```


## Search for Best Configuration

```{r, echo = TRUE}
M1 <- 1
M2 <- 100000
Xsum <- sapply(M1:M2, red_and_black)
names(Xsum) <- M1:M2
```

## Summary

```{r, summary, echo = TRUE}
Xsum %>%
  summary %>%
  round(2) 
Xsum %>%
  sd %>%
  round(2)
Xsum %>%
  `<=`(9) %>%
  which %>%
  `[`(Xsum, .) %>%
  round(2)
Xmin <- names(Xsum[which(Xsum == min(Xsum))])
Xmin
```

## Plot

```{r, echo = FALSE}
hist(Xsum, prob = TRUE, nclass = 30, xlim = c(0, 70), ylim = c(0, 0.06))
x <- seq(0, 70, by = 0.1)
lines(x, dchisq(x, df = 32), col = "red")
legend("topright", inset = 0.05, legend = c("Xsum", "Chi-square(32)"), col = c("black", "red"), lty = 1)
plot(density(Xsum), xlim = c(0, 70), ylim = c(0, 0.06), main = "Density Estimation of Xsum")
lines(x, dchisq(x, df = 32), col = "red")
legend("topright", inset = 0.05, legend = c("Xsum", "Chi-square(32)"), col = c("black", "red"), lty = 1)
```

## ggplot

```{r, ggplot, echo = FALSE, eval = TRUE}
library(ggplot2)

# Xsum 히스토그램 및 카이제곱 분포 곡선 추가
ggplot(data.frame(Xsum = Xsum), aes(x = Xsum)) +
  # 히스토그램 (범례에 검은색 테두리로 표시)
  geom_histogram(aes(y = after_stat(density), color = "Xsum"), bins = 30, fill = NA, linewidth = 0.5, na.rm = TRUE) +  
  
  # Chi-square(32) 분포 (붉은 선으로 설정)
  stat_function(fun = dchisq, args = list(df = 32), aes(color = "Chi-square(32)"), linewidth = 0.5) +
  
  # 축 범위 설정
  xlim(0, 70) + ylim(0, 0.06) +
  
  # 제목과 축 라벨 설정
  labs(title = "Histogram of Xsum", x = "Xsum", y = "Density") +
  
  # 수동 색상 설정 (Xsum은 검은색, Chi-square(32)은 빨간색)
  scale_color_manual(values = c("Chi-square(32)" = "red", "Xsum" = "black"), 
                     name = NULL,
                     labels = c("Chi-square(32) Density", "Histogram of Xsum")) +
  
  # 범례를 선 스타일로 표시
  guides(color = guide_legend(override.aes = list(linetype = c("solid", "solid"), 
                                                   fill = c(NA, NA),  # 히스토그램도 선으로 나타내기 위해
                                                   size = 1))) +
  
  # 미니멀 테마와 플롯 타이틀 가운데 정렬
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        panel.border = element_rect(color = "black", fill = NA),
        legend.position = "inside",
        legend.position.inside = c(0.8, 0.8),                            # 범례를 플롯 내부에 배치
        legend.box = "rect",                                      # 범례를 박스로 설정
        legend.background = element_rect(color = "black")) 


# Density Estimation
ggplot(data.frame(Xsum = Xsum), aes(x = Xsum)) +
  # Xsum의 밀도 추정 곡선 (검은색)
  geom_density(aes(color = "Xsum"), linetype = "solid", linewidth = 0.5, na.rm = TRUE) +
  
  # Chi-square(32)의 카이제곱 분포 곡선 (붉은색)
  stat_function(fun = dchisq, args = list(df = 32), aes(color = "Chi-square(32)"), linetype = "solid", linewidth = 0.5) +
  
  # 축 범위 설정
  xlim(0, 70) + ylim(0, 0.06) +
  
  # 제목과 축 라벨 설정
  labs(title = "Density Estimation of Xsum", x = "Xsum", y = "Density") +
  
  # 색상 수동 설정
  scale_color_manual(values = c("Chi-square(32)" = "red", "Xsum" = "black"), 
                     name = NULL, 
                     labels = c("Chi-square(32) Density", "Smoothed Xsum")) +
  
  # 범례를 선 스타일로 변경
   guides(color = guide_legend(override.aes = list(linetype = "solid", 
                                                   fill = NA,  # 선 색상 유지
                                                   linewidth = 0.5))) +  # 선 높이
  
  # 미니멀 테마 및 범례 스타일 설정
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        panel.border = element_rect(color = "black", fill = NA),     # 플롯 테두리 박스 설정
        legend.position = "inside",
        legend.position.inside = c(0.8, 0.8), 
        legend.box = "rect",                                        # 범례를 박스로 설정
        legend.background = element_rect(color = "black", fill = NA),
        legend.key = element_blank())  # 범례 키 박스 제거 
```

<!--
## Randomization

```{r, randomization}
set.seed(Xmin)
N <- nrow(class_roll) 
class_roll$group <- 
  sample(1:N) %%
  2 %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
red_and_black(Xmin)
```

### 학년

```{r, year, eval = FALSE}
tbl0 <- class_roll$year %>%
  table(class_roll$group, .) 
tbl0 %>%
  pander
X0min <- tbl0 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X0min
```
-->

## 학번

```{r, id, echo = FALSE, eval = TRUE}
class_roll$id_2 <-
  class_roll$id %>%
  substr(1, 4) %>%
  ifelse(. <= 2018, "2018", .)
tbl1 <- class_roll %$%
  table(.$group, .$id_2) %>%
  `colnames<-`(c("2018 이전", 2019:2024)) 
tbl1 %>%
  pander
# X1min <- tbl1 %>%
#   chisq.test(simulate.p.value = TRUE) %>%
#   `[[`(1)
# X1min
```

<!--
### 학번 홀짝

```{r, odd or even, eval = FALSE}
tbl2 <- class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) 
tbl2 %>%
  pander
X2min <- tbl2 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X2min
```

### 학적 상태

```{r, status, eval = FALSE}
tbl3 <- class_roll$status %>%
  table(class_roll$group, .) 
tbl3 %>%
  pander
X3min <- tbl3 %>%
  chisq.test(simulate.p.value = TRUE) %>%
  `[[`(1)
X3min
```
-->

## e-mail 서비스업체

```{r, e_mail, echo = FALSE, eval = TRUE}
isp <- class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  strsplit("[.]", fixed = FALSE) %>%
  sapply("[", 1)
tbl4 <- isp %>%
  `%in%`(c("naver", "gmail")) %>%
  ifelse(isp, "기타서비스") %>%
  factor(levels = c("naver", "gmail", "기타서비스"),
         labels = c("네이버", "구글", "기타서비스")) %>%
  table(class_roll$group, .) 
tbl4 %>%
  pander
# X4min <- tbl4 %>%
#   chisq.test(simulate.p.value = FALSE) %>%
#   `[[`(1)
# X4min
```

## 전화번호의 분포

```{r, cell_no, echo = FALSE, eval = TRUE}
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
tbl5 <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric) %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) 
tbl5 %>%
  pander
# X5min <- tbl5 %>%
#   chisq.test(simulate.p.value = TRUE) %>%
#   `[[`(1)
# X5min
```

## 성씨 분포

```{r, name, echo = FALSE, eval = TRUE}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
tbl6 <- f_name %>%
  `%in%`(c("김", "이", "박", "최", "정")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "최", "정", "기타")) %>%
  table(class_roll$group, .) 
tbl6 %>%
  pander
# X6min <- tbl6 %>%
#   chisq.test(simulate.p.value = TRUE) %>%
#   `[[`(1)
# X6min
```

## 단과대학

```{r, college, echo = FALSE, eval = TRUE}
tbl7 <- 
  class_roll %$%
  table(.$group, .$college) 
tbl7 %>%
  pander
# X7min <- tbl7 %>%
#   chisq.test(simulate.p.value = TRUE) %>%
#   `[[`(1) 
# X7min
```

<!--
### Sum of Chi_Squares

```{r, eval = FALSE}
# Xsum_min <- X0min + X1min + X2min + X3min + X4min + X5min + X6min + X7min
Xsum_min <- X1min + X7min
Xsum_min
```
-->

<!--
```{r, save}
save.image("./red_and_black_optimum_data_240824_v5_0_1.RData")
```
-->